// Editá este listado con tus prendas reales.
// Colocá las fotos dentro de la carpeta "img" al lado de este archivo.
// Por ejemplo: img/remera-blanca.jpg

window.PRODUCTOS = [
  {
    nombre: "Calza clásica Adidas",
    categoria: "Calzas",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "Calza clásica Adidas 1.jpeg",
  },
  {
    nombre: "Calza clásica Adidas",
    categoria: "Calzas",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "Calza clásica Adidas 2.jpeg",
  },
  {
    nombre: "Calza clásica Adidas",
    categoria: "Calzas",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "Calza clásica Adidas 3.jpeg",
  },
  {
    nombre: "Calza Go Lycra",
    categoria: "Calzas",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "Calza Go Lycra.jpeg",
  },
  {
    nombre: "Calzas GO",
    categoria: "Calzas",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "CALZAS GO 1.jpeg",
  },
  {
    nombre: "Calzas GO",
    categoria: "Calzas",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "CALZAS GO 2.jpeg",
  },
  {
    nombre: "Calzas GO",
    categoria: "Calzas",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "CALZAS GO 3.jpeg",
  },
  {
    nombre: "Musculosa espalda cruz",
    categoria: "Musculosas",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Lila",
    imagen: "Musculosa espalda cruz Atras.jpeg",
  },
  {
    nombre: "Musculosa espalda cruz",
    categoria: "Musculosas",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Lila",
    imagen: "Musculosa espalda cruz.jpeg",
  },
  {
    nombre: "Remera Prime Unisex",
    categoria: "Remeras",
    precio: 0,
    talles: ["S", "M", "L", "XL"],
    color: "Gris topo",
    imagen: "Remera Prime Unisex Gris Topo.jpeg",
  },
  {
    nombre: "Remera Prime Unisex",
    categoria: "Remeras",
    precio: 0,
    talles: ["S", "M", "L", "XL"],
    color: "Negro",
    imagen: "Remera Prime Unisex Negro.jpeg",
  },
  {
    nombre: "Short con calza Adidas",
    categoria: "Shorts",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "Short con calza Adidas 1.jpeg",
  },
  {
    nombre: "Short con calza Adidas",
    categoria: "Shorts",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "Short con calza Adidas 2.jpeg",
  },
  {
    nombre: "Short con calza Adidas",
    categoria: "Shorts",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "Short con calza Adidas 3.jpeg",
  },
  {
    nombre: "Short con calza Adidas",
    categoria: "Shorts",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "Short con calza Adidas 4.jpeg",
  },
  {
    nombre: "Short con calza Adidas",
    categoria: "Shorts",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "Short con calza Adidas 5.jpeg",
  },
  {
    nombre: "Short Nike 365",
    categoria: "Shorts",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Negro",
    imagen: "SHORT NIKE 365 2.jpeg",
  },
  {
    nombre: "Short Nike 365",
    categoria: "Shorts",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Negro",
    imagen: "SHORT NIKE 365 3.jpeg",
  },
  {
    nombre: "Short Nike 365",
    categoria: "Shorts",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Negro",
    imagen: "Short Nike 365.jpeg",
  },
  {
    nombre: "Sudadera Training",
    categoria: "Tops",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Negro",
    imagen: "Sudadera Training 1.jpeg",
  },
  {
    nombre: "Sudadera Training",
    categoria: "Tops",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Negro",
    imagen: "Sudadera Training.jpeg",
  },
  {
    nombre: "Top deportivo Adidas Kai",
    categoria: "Tops",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "Top deportivo Adidas kai 1.jpeg",
  },
  {
    nombre: "Top deportivo Adidas Kai",
    categoria: "Tops",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "Top deportivo Adidas kai 2.jpeg",
  },
  {
    nombre: "Top deportivo Adidas Kai",
    categoria: "Tops",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "Top deportivo Adidas kai 3.jpeg",
  },
  {
    nombre: "Top deportivo Adidas Kai",
    categoria: "Tops",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "Top deportivo Adidas kai 4.jpeg",
  },
  {
    nombre: "Top deportivo Adidas Kai",
    categoria: "Tops",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "Top deportivo Adidas kai 5.jpeg",
  },
  {
    nombre: "Top deportivo Adidas Kai",
    categoria: "Tops",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "Top deportivo Adidas kai 6.jpeg",
  },
  {
    nombre: "Top deportivo Adidas Kai",
    categoria: "Tops",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "Top deportivo Adidas kai 7.jpeg",
  },
  {
    nombre: "Top deportivo Adidas Kai",
    categoria: "Tops",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "Top deportivo Adidas kai 8.jpeg",
  },
  {
    nombre: "Top deportivo Adidas Kai",
    categoria: "Tops",
    precio: 0,
    talles: ["S", "M", "L"],
    color: "Varios colores",
    imagen: "Top deportivo Adidas kai 9.jpeg",
  },
];

